site_name: CRDDM
site_author: Amir Hosein Hadian
site_description: Continuous Response Diffusion Decision Models (CRDDM) - documentation
repo_name: AmirHoseinHadian/CRDDM
repo_url: https://github.com/AmirHoseinHadian/CRDDM
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
      - Quickstart: tutorials/quickstart.md
      - Design Specification: tutorials/design_spesification.md
      - Custom Mapping Function: tutorials/custom_mapping_function.md
      - Collapsing Threshold Models: tutorials/collapsing_threshold_models.md
      - Custom Threshold Dynamics: tutorials/custom_threshold_dynamics.md
      - Mixture Models: tutorials/mixture_models.md
      - Model Comparison: tutorials/model_comparison.md
  - API Reference: api.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_source: true
            show_signature_annotations: true
            merge_init_into_class: true
            docstring_style: numpy
            docstring_section_style: table

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - javascripts/katex.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

